### ISSUE TITLE
Can't add series after view creation

### ISSUE THREAD

**Issue by Erhannis** [halfhp/androidplot#17]
Once the view is created, I can no longer add series to the plot.  This is problematic because I'm asynchronously loading data from a server, and can't add the series until the data gets back.

To be slightly more detailed, if I add series during view creation, they show up fine.  If I add series afterwards, however, the plot shows no change.

**Comment by Erhannis** [comment]
Ah, nevermind.  (Plot).redraw() is what I needed.

**Comment by GremlinsInGame** [comment]
Holy crap...  This has plagued me for Hours!!!   Hours!.
I could load data when I launched the activity with the Plot but couldnt load a Series after that.
Why the heck wouldn't the plot redraw **itself** after adding a Series.?
In my case, I need to open a file and load the dataseries after the plot view has been loaded for a while and was blank..

**Comment by halfhp** [comment]
> Why the heck wouldn't the plot redraw itself after adding a Series

Primarily because it's inefficient and ugly.  Androidplot has no way of knowing whether you're adding one series or ten.  The same expectation could be placed on any layout changes such as font or color changes, etc.  If it were to redraw its self after each addition or layout change the result would produce ugly flickering / resizing effects instead of a single smooth update.
