### ISSUE TITLE
Number Exception with fillPaintColor

### ISSUE THREAD

**Issue by mkonchady** [halfhp/androidplot#63]
In Androidplot 1.5.1, I got a NumberException with the fillPaintColor set to #00000000 in the code below. It works when the fillPaintColor is set to #000000. A work around is to manually call the setFillPaint method.

`LineAndPointFormatter averageFormat = new LineAndPointFormatter();
 averageFormat.setPointLabelFormatter(new PointLabelFormatter());
 averageFormat.configure(context, R.xml.plot_average_line);
`
plot_average_line
`<?xml version="1.0" encoding="utf-8"?>
<config
    linePaint.strokeWidth="2dp"
    linePaint.color="@color/IndianRed"
    vertexPaint.color="@color/IndianRed"
    vertexPaint.strokeWidth="2dp"
    fillPaint.color="#00000000"/>`

**Comment by halfhp** [comment]
The root cause appears to be some undocumented change to the Gradle plugin in 3.0.x. (I'm going to go out on a limb and say your project is using that)

A short term fix is to downrev the Gradle plugin.  The permanent fix will be available in Androidplot 1.5.2 which should be released a little later this week.
